/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#0f172a",
        "surface-dim": "#020617",
        "surface-bright": "#1e293b",
        "surface-container-lowest": "#020617",
        "surface-container-low": "#0f172a",
        "surface-container": "#131c2e",
        "surface-container-high": "#1a2332",
        "surface-container-highest": "#222d3f",
        "on-surface": "#f8fafc",
        "on-surface-variant": "#94a3b8",
        outline: "#334155",
        "outline-variant": "#1e293b",
        "surface-tint": "#22c55e",
        primary: "#22c55e",
        "on-primary": "#0f172a",
        "primary-container": "#16a34a",
        "on-primary-container": "#052e16",
        secondary: "#fbbf24",
        "on-secondary": "#451a03",
        "secondary-container": "#f59e0b",
        "on-secondary-container": "#3b1f03",
        tertiary: "#f472b6",
        "on-tertiary": "#500724",
        "tertiary-container": "#db2777",
        "on-tertiary-container": "#4a0e2e",
        error: "#ef4444",
        "on-error": "#000000",
        "error-container": "#b91c1c",
        "on-error-container": "#fef2f2",
        background: "#020617",
        "on-background": "#f8fafc",
        "surface-variant": "#1a1e2f",
      },
      fontFamily: {
        display: ["var(--font-geist)", "sans-serif"],
        sans: ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em" }],
        "body-base": ["16px", { lineHeight: "24px" }],
        "body-sm": ["14px", { lineHeight: "20px" }],
        "mono-code": ["13px", { lineHeight: "20px" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em" }],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        container: "24px",
        gutter: "16px",
        section: "32px",
        "component-x": "12px",
        "component-y": "8px",
      },
    },
  },
  plugins: [],
}
